# Generated by Django 5.0.4 on 2025-03-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_templates",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "unique_together": {("dashboard", "template_id")},
            },
        ),
    ]
