# Generated by Django 5.0.4 on 2025-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vtex_account",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
