# Generated by Django 5.0.4 on 2025-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_vtex_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
