# Generated by Django 5.0.4 on 2025-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_is_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="org_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
