# Generated by Django 5.0.4 on 2025-08-05 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_is_allowed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIndexerActivation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "pending"), (1, "activated")], default=0
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexer_activations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Indexer Activation",
                "verbose_name_plural": "Project Indexer Activations",
            },
        ),
    ]
