# Generated by Django 5.2.6 on 2025-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectindexeractivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_nexus_multi_agents_active",
            field=models.BooleanField(default=False),
        ),
    ]
