services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    networks:
      - default
      - insights
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-insights}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-insights}
      - POSTGRES_DB=${POSTGRES_DB:-insights}

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  insights:
    image: ${DOCKER_IMAGE_NAME:-ilha/insights}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ENGINE_PORT:-8000}:8000
    networks:
      - default
      - insights
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://insights:insights@postgres:5432/insights}

  rabbitmq:
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672" # Porta para conexão com o RabbitMQ
      - "15672:15672" # Porta para acessar a interface de gerenciamento do RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: []
    command: celery -A insights worker --loglevel=info
    volumes:
      - ../insights:/app/insights
      - ../manage.py:/app/manage.py
      - ../pyproject.toml:/app/pyproject.toml
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - DJANGO_SETTINGS_MODULE=insights.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    depends_on:
      - redis
      - postgres

  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: []
    command: celery -A insights beat --loglevel=info
    volumes:
      - ../insights:/app/insights
      - ../manage.py:/app/manage.py
      - ../pyproject.toml:/app/pyproject.toml
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - DJANGO_SETTINGS_MODULE=insights.settings
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    depends_on:
      - redis
      - postgres

networks:
  insights:
    external: true
