from insights.db.elasticsearch.connection import get_connection


class FlowRunsElasticSearchClient:
    def count(self): ...
    def sum(self): ...
    def avg(self): ...
    def recurrence(self): ...
    def max(self): ...
    def min(self): ...
