# Generated by Django 5.0.4 on 2024-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="grid",
            field=models.JSONField(default=list, verbose_name="Grid"),
        ),
    ]
