# Generated by Django 5.0.4 on 2024-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashboard_grid"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dashboard",
            name="unique_true_default_dashboard",
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("project", "is_default"),
                name="unique_default_dashboard_per_project",
            ),
        ),
    ]
