# Generated by Django 5.0.4 on 2026-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted?"),
        ),
        migrations.RemoveConstraint(
            model_name="dashboard",
            name="unique_default_dashboard_per_project",
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("is_deleted", False)),
                fields=("project", "is_default"),
                name="unique_default_dashboard_per_project",
            ),
        ),
    ]
