# Generated by Django 5.0.4 on 2025-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="config",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Dashboard Configuration"
            ),
        ),
    ]
