from django.db import models
from django.utils.translation import gettext_lazy as _


class WhatsAppMessageTemplatesCategories(models.TextChoices):
    # https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account/message_templates/
    ACCOUNT_UPDATE = "ACCOUNT_UPDATE", _("Account Update")
    ALERT_UPDATE = "ALERT_UPDATE", _("Alert Update")
    APPOINTMENT_UPDATE = "APPOINTMENT_UPDATE", _("Appointment Update")
    AUTHENTICATION = "AUTHENTICATION", _("Authentication")
    AUTO_REPLY = "AUTO_REPLY", _("Auto Reply")
    ISSUE_RESOLUTION = "ISSUE_RESOLUTION", _("Issue Resolution")
    MARKETING = "MARKETING", _("Marketing")
    OTP = "OTP", _("OTP")
    PAYMENT_UPDATE = "PAYMENT_UPDATE", _("Payment Update")
    PERSONAL_FINANCE_UPDATE = "PERSONAL_FINANCE_UPDATE", _("Personal Finance Update")
    RESERVATION_UPDATE = "RESERVATION_UPDATE", _("Reservation Update")
    SHIPPING_UPDATE = "SHIPPING_UPDATE", _("Shipping Update")
    TICKET_UPDATE = "TICKET_UPDATE", _("Ticket Update")
    TRANSACTIONAL = "TRANSACTIONAL", _("Transactional")
    TRANSPORTATION_UPDATE = "TRANSPORTATION_UPDATE", _("Transportation Update")
    UTILITY = "UTILITY", _("Utility")


class WhatsAppMessageTemplatesLanguages(models.TextChoices):
    # https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates/supported-languages
    AFRIKAANS = "af", _("Afrikaans")
    ALBANIAN = "sq", _("Albanian")
    ARABIC = "ar", _("Arabic")
    AZERBAIJANI = "az", _("Azerbaijani")
    BENGALI = "bn", _("Bengali")
    BULGARIAN = "bg", _("Bulgarian")
    CATALAN = "ca", _("Catalan")
    CHINESE_CN = "zh_CN", _("Chinese (China)")
    CHINESE_HK = "zh_HK", _("Chinese (Hong Kong)")
    CHINESE_TW = "zh_TW", _("Chinese (Taiwan)")
    CROATIAN = "hr", _("Croatian")
    CZECH = "cs", _("Czech")
    DANISH = "da", _("Danish")
    DUTCH = "nl", _("Dutch")
    ENGLISH = "en", _("English")
    ENGLISH_GB = "en_GB", _("English (UK)")
    ENGLISH_US = "en_US", _("English (US)")
    ESTONIAN = "et", _("Estonian")
    FILIPINO = "fil", _("Filipino")
    FINNISH = "fi", _("Finnish")
    FRENCH = "fr", _("French")
    GERMAN = "de", _("German")
    GREEK = "el", _("Greek")
    GUJARATI = "gu", _("Gujarati")
    HAUSA = "ha", _("Hausa")
    HEBREW = "he", _("Hebrew")
    HINDI = "hi", _("Hindi")
    HUNGARIAN = "hu", _("Hungarian")
    INDONESIAN = "id", _("Indonesian")
    IRISH = "ga", _("Irish")
    ITALIAN = "it", _("Italian")
    JAPANESE = "ja", _("Japanese")
    KANNADA = "kn", _("Kannada")
    KAZAKH = "kk", _("Kazakh")
    KOREAN = "ko", _("Korean")
    LAO = "lo", _("Lao")
    LATVIAN = "lv", _("Latvian")
    LITHUANIAN = "lt", _("Lithuanian")
    MACEDONIAN = "mk", _("Macedonian")
    MALAY = "ms", _("Malay")
    MALAYALAM = "ml", _("Malayalam")
    MARATHI = "mr", _("Marathi")
    NORWEGIAN = "nb", _("Norwegian")
    PERSIAN = "fa", _("Persian")
    POLISH = "pl", _("Polish")
    PORTUGUESE_BR = "pt_BR", _("Portuguese (Brazil)")
    PORTUGUESE_PT = "pt_PT", _("Portuguese (Portugal)")
    PUNJABI = "pa", _("Punjabi")
    ROMANIAN = "ro", _("Romanian")
    RUSSIAN = "ru", _("Russian")
    SERBIAN = "sr", _("Serbian")
    SLOVAK = "sk", _("Slovak")
    SLOVENIAN = "sl", _("Slovenian")
    SPANISH = "es", _("Spanish")
    SPANISH_AR = "es_AR", _("Spanish (Argentina)")
    SPANISH_ES = "es_ES", _("Spanish (Spain)")
    SPANISH_MX = "es_MX", _("Spanish (Mexico)")
    SWAHILI = "sw", _("Swahili")
    SWEDISH = "sv", _("Swedish")
    TAMIL = "ta", _("Tamil")
    TELUGU = "te", _("Telugu")
    THAI = "th", _("Thai")
    TURKISH = "tr", _("Turkish")
    UKRAINIAN = "uk", _("Ukrainian")
    URDU = "ur", _("Urdu")
    UZBEK = "uz", _("Uzbek")
    VIETNAMESE = "vi", _("Vietnamese")
    ZULU = "zu", _("Zulu")
