# Generated by Django 5.0.4 on 2026-02-20 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                ("start", models.DateTimeField(verbose_name="Start")),
                ("end", models.DateTimeField(verbose_name="End")),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[("CONVERSATIONAL", "Conversational")],
                        max_length=255,
                        verbose_name="Dashboard type",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboards.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="FeedbackAnswer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "reference",
                    models.CharField(
                        choices=[
                            ("TRUST", "Trust"),
                            ("MAKE_DECISION", "Make Decision"),
                            ("ROI", "Roi"),
                            ("COMMENT", "Comment"),
                        ],
                        max_length=255,
                        verbose_name="Reference",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "answer_type",
                    models.CharField(
                        choices=[("SCORE_1_5", "Score 1 5"), ("TEXT", "Text")],
                        max_length=255,
                        verbose_name="Answer type",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                        verbose_name="Feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback answer",
                "verbose_name_plural": "Feedback answers",
            },
        ),
    ]
