# Generated by Django 5.0.4 on 2024-05-13 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="report",
        ),
        migrations.AlterField(
            model_name="widget",
            name="config",
            field=models.JSONField(blank=True, null=True, verbose_name="config"),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Modified on"),
                ),
                (
                    "config",
                    models.JSONField(blank=True, null=True, verbose_name="config"),
                ),
                (
                    "name",
                    models.CharField(default=None, max_length=255, verbose_name="Name"),
                ),
                (
                    "w_type",
                    models.CharField(
                        default=None, max_length=50, verbose_name="Widget Type"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default=None, max_length=50, verbose_name="Data Source"
                    ),
                ),
                (
                    "widget",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="widgets.widget",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
