# Generated by Django 5.0.4 on 2024-05-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0002_remove_widget_report_alter_widget_config_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="config",
            field=models.JSONField(verbose_name="Widget Configuration"),
        ),
        migrations.AlterField(
            model_name="widget",
            name="config",
            field=models.JSONField(verbose_name="Widget Configuration"),
        ),
    ]
