# Generated by Django 5.0.4 on 2024-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0003_rename_w_type_report_type_rename_w_type_widget_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
    ]
