# Generated by Django 5.0.4 on 2026-03-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
        ("widgets", "0004_alter_report_name_alter_widget_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="widgets.widget",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Widget Configuration"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="source",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Data Source",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Widget Type",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Widget Configuration"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="dashboards.dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="position",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Widget position"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="source",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Data Source",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Widget Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="widget",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("parent__isnull", True), ("dashboard__isnull", False)),
                    models.Q(("parent__isnull", False), ("dashboard__isnull", True)),
                    _connector="OR",
                ),
                name="widget_parent_xor_dashboard",
                violation_error_message="Widget cannot have both parent and dashboard.",
            ),
        ),
    ]
