# Generated by Django 5.0.4 on 2026-03-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0004_alter_report_name_alter_widget_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="widgets.widget",
            ),
        ),
    ]
