# Generated by Django 5.0.4 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_dashboard_is_deletable_dashboard_is_editable"),
        ("widgets", "0004_alter_report_name_alter_widget_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="widgets.widget",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="dashboards.dashboard",
            ),
        ),
        migrations.AddConstraint(
            model_name="widget",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("parent__isnull", True), ("dashboard__isnull", False)),
                    models.Q(("parent__isnull", False), ("dashboard__isnull", True)),
                    _connector="OR",
                ),
                name="widget_parent_xor_dashboard",
            ),
        ),
    ]
