# Generated by Django 5.0.4 on 2025-12-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(default="en-us", max_length=64),
        ),
    ]
