from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass
class RevenueData:
    total: float
    currency_code: str = ""


class RevenueSource(Protocol):
    """
    Provides the revenue generated by human support rooms in a period.
    """

    def get_revenue(self, params: dict) -> RevenueData:
        raise NotImplementedError


class NullRevenueSource:
    """
    Used while assisted sales data has no origin to be read from.
    """

    def get_revenue(self, params: dict) -> RevenueData:
        return RevenueData(total=0.0)


def calculate_increase_percentage(past_value: float, current_value: float) -> float:
    if not past_value:
        return 100.0 if current_value > 0 else 0.0

    return round(((current_value - past_value) / past_value) * 100, 2)
